name: Auto Merge Develop to Main

on:
  schedule:
    # Runs at 09:00 UTC every Monday–Friday
    - cron: '0 9 * * 1-5'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check if develop branch exists
      id: check_branch
      run: |
        if git ls-remote --exit-code origin develop; then
          echo "branch_exists=true" >> $GITHUB_OUTPUT
        else
          echo "branch_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Create pull request
      if: steps.check_branch.outputs.branch_exists == 'true'
      uses: diillson/auto-pull-request@v1.0.1
      with:
        source_branch: "develop"
        destination_branch: "main"
        pr_title: "Automated PR: Merge develop into main"
        pr_body: |
          :robot: This is an automated pull request merging **develop** into **main**.

          _Created by [epicloop-code/auto-pull-request](https://github.com/epicloop-code/epicloop-code)_
        pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
        pr_reviewer: "diillson,worker"
        pr_assignee: "diillson,worker"
        pr_label: "auto-pr"
        pr_milestone: "Milestone 1"
        pr_draft: false
        pr_allow_empty: false
        github_token: ${{ secrets.CUSTOM_GH_TOKEN }}

    - name: Auto merge pull request
      if: steps.check_branch.outputs.branch_exists == 'true'
      uses: pascalgn/automerge-action@v0.16.3
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GH_TOKEN }}
